"""empty message

Revision ID: 574b5219254a
Revises: 8048811e4b46
Create Date: 2025-04-05 00:29:38.302729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574b5219254a'
down_revision = '8048811e4b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unread', sa.Integer(), nullable=False),
    sa.Column('read', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)
        batch_op.drop_constraint('post_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('post_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('messages')
    op.drop_table('friends')
    # ### end Alembic commands ###
